language: node_js
node_js: stable

install:
  - npm install
  
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "rjgeek"
  - git config user.email "rxl635@student.bham.ac.uk"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - code
env:
 global:
   - GH_REF: github.com/rjgeek/rjgeek.github.io.git
